// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ServerEmotesColumns holds the columns for the "server_emotes" table.
	ServerEmotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "server_id", Type: field.TypeString},
		{Name: "emote_id", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "image_type", Type: field.TypeString},
	}
	// ServerEmotesTable holds the schema information for the "server_emotes" table.
	ServerEmotesTable = &schema.Table{
		Name:       "server_emotes",
		Columns:    ServerEmotesColumns,
		PrimaryKey: []*schema.Column{ServerEmotesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ServerEmotesTable,
	}
)

func init() {
}
