// Code generated by entc, DO NOT EDIT.

package serveremote

const (
	// Label holds the string label denoting the serveremote type in the database.
	Label = "server_emote"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServerID holds the string denoting the server_id field in the database.
	FieldServerID = "server_id"
	// FieldEmoteID holds the string denoting the emote_id field in the database.
	FieldEmoteID = "emote_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldImageType holds the string denoting the image_type field in the database.
	FieldImageType = "image_type"
	// Table holds the table name of the serveremote in the database.
	Table = "server_emotes"
)

// Columns holds all SQL columns for serveremote fields.
var Columns = []string{
	FieldID,
	FieldServerID,
	FieldEmoteID,
	FieldCode,
	FieldImageType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
