// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"betterdsc/ent/migrate"

	"betterdsc/ent/serveremote"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ServerEmote is the client for interacting with the ServerEmote builders.
	ServerEmote *ServerEmoteClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ServerEmote = NewServerEmoteClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		ServerEmote: NewServerEmoteClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		ServerEmote: NewServerEmoteClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ServerEmote.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ServerEmote.Use(hooks...)
}

// ServerEmoteClient is a client for the ServerEmote schema.
type ServerEmoteClient struct {
	config
}

// NewServerEmoteClient returns a client for the ServerEmote from the given config.
func NewServerEmoteClient(c config) *ServerEmoteClient {
	return &ServerEmoteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `serveremote.Hooks(f(g(h())))`.
func (c *ServerEmoteClient) Use(hooks ...Hook) {
	c.hooks.ServerEmote = append(c.hooks.ServerEmote, hooks...)
}

// Create returns a create builder for ServerEmote.
func (c *ServerEmoteClient) Create() *ServerEmoteCreate {
	mutation := newServerEmoteMutation(c.config, OpCreate)
	return &ServerEmoteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ServerEmote entities.
func (c *ServerEmoteClient) CreateBulk(builders ...*ServerEmoteCreate) *ServerEmoteCreateBulk {
	return &ServerEmoteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ServerEmote.
func (c *ServerEmoteClient) Update() *ServerEmoteUpdate {
	mutation := newServerEmoteMutation(c.config, OpUpdate)
	return &ServerEmoteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ServerEmoteClient) UpdateOne(se *ServerEmote) *ServerEmoteUpdateOne {
	mutation := newServerEmoteMutation(c.config, OpUpdateOne, withServerEmote(se))
	return &ServerEmoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ServerEmoteClient) UpdateOneID(id int) *ServerEmoteUpdateOne {
	mutation := newServerEmoteMutation(c.config, OpUpdateOne, withServerEmoteID(id))
	return &ServerEmoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ServerEmote.
func (c *ServerEmoteClient) Delete() *ServerEmoteDelete {
	mutation := newServerEmoteMutation(c.config, OpDelete)
	return &ServerEmoteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ServerEmoteClient) DeleteOne(se *ServerEmote) *ServerEmoteDeleteOne {
	return c.DeleteOneID(se.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ServerEmoteClient) DeleteOneID(id int) *ServerEmoteDeleteOne {
	builder := c.Delete().Where(serveremote.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ServerEmoteDeleteOne{builder}
}

// Query returns a query builder for ServerEmote.
func (c *ServerEmoteClient) Query() *ServerEmoteQuery {
	return &ServerEmoteQuery{
		config: c.config,
	}
}

// Get returns a ServerEmote entity by its id.
func (c *ServerEmoteClient) Get(ctx context.Context, id int) (*ServerEmote, error) {
	return c.Query().Where(serveremote.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ServerEmoteClient) GetX(ctx context.Context, id int) *ServerEmote {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ServerEmoteClient) Hooks() []Hook {
	return c.hooks.ServerEmote
}
