// Code generated by entc, DO NOT EDIT.

package ent

import (
	"betterdsc/ent/predicate"
	"betterdsc/ent/serveremote"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerEmoteDelete is the builder for deleting a ServerEmote entity.
type ServerEmoteDelete struct {
	config
	hooks    []Hook
	mutation *ServerEmoteMutation
}

// Where appends a list predicates to the ServerEmoteDelete builder.
func (sed *ServerEmoteDelete) Where(ps ...predicate.ServerEmote) *ServerEmoteDelete {
	sed.mutation.Where(ps...)
	return sed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sed *ServerEmoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sed.hooks) == 0 {
		affected, err = sed.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServerEmoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sed.mutation = mutation
			affected, err = sed.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sed.hooks) - 1; i >= 0; i-- {
			if sed.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sed.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sed.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sed *ServerEmoteDelete) ExecX(ctx context.Context) int {
	n, err := sed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sed *ServerEmoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: serveremote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: serveremote.FieldID,
			},
		},
	}
	if ps := sed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sed.driver, _spec)
}

// ServerEmoteDeleteOne is the builder for deleting a single ServerEmote entity.
type ServerEmoteDeleteOne struct {
	sed *ServerEmoteDelete
}

// Exec executes the deletion query.
func (sedo *ServerEmoteDeleteOne) Exec(ctx context.Context) error {
	n, err := sedo.sed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{serveremote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sedo *ServerEmoteDeleteOne) ExecX(ctx context.Context) {
	sedo.sed.ExecX(ctx)
}
