// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ServerEmote is the predicate function for serveremote builders.
type ServerEmote func(*sql.Selector)
